import 'dart:convert';
import 'dart:io';
import 'package:flutter/material.dart';
import 'package:file_selector/file_selector.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:http/http.dart' as http;
import 'package:syncfusion_flutter_pdf/pdf.dart';

class UpdatesPage extends StatefulWidget {
  const UpdatesPage({Key? key}) : super(key: key);

  @override
  State<UpdatesPage> createState() => _UpdatesPageState();
}

class _UpdatesPageState extends State<UpdatesPage>
    with SingleTickerProviderStateMixin {
  bool isLoading = false;
  final String sambaApiKey = "2ee6e6d1-ed57-45c2-b73d-e6d7304815aa";

  // ===============================
  // MAIN PROCESS
  // ===============================
  Future<void> pickAndProcessFile() async {
    try {
      setState(() => isLoading = true);

      final typeGroup = XTypeGroup(
        label: 'PDF',
        extensions: ['pdf'],
      );

      final XFile? file =
      await openFile(acceptedTypeGroups: [typeGroup]);

      if (file == null) {
        setState(() => isLoading = false);
        return;
      }

      File localFile = File(file.path);
      String extractedText = await extractTextFromPdf(localFile);

      Map<String, dynamic> result =
      await generateDosDontsFromSamba(extractedText);

      List dos = result["dos"] ?? [];
      List donts = result["donts"] ?? [];

      await FirebaseFirestore.instance.collection("directives").add({
        "fileName": file.name,
        "rawText": extractedText,
        "dos": dos,
        "donts": donts,
        "generatedBy": "AI",
        "createdAt": FieldValue.serverTimestamp(),
      });

      setState(() => isLoading = false);
      showPremiumPopup(dos, donts);
    } catch (e) {
      setState(() => isLoading = false);
      ScaffoldMessenger.of(context)
          .showSnackBar(SnackBar(content: Text("Error: $e")));
    }
  }

  Future<String> extractTextFromPdf(File file) async {
    final bytes = file.readAsBytesSync();
    final PdfDocument document = PdfDocument(inputBytes: bytes);
    final String text = PdfTextExtractor(document).extractText();
    document.dispose();
    return text;
  }

  Future<Map<String, dynamic>> generateDosDontsFromSamba(
      String text) async {
    final url =
    Uri.parse("https://api.sambanova.ai/v1/chat/completions");

    final response = await http.post(
      url,
      headers: {
        "Authorization": "Bearer $sambaApiKey",
        "Content-Type": "application/json"
      },
      body: jsonEncode({
        "model": "Meta-Llama-3.1-8B-Instruct",
        "messages": [
          {
            "role": "user",
            "content":
            "Extract Do's and Don'ts clearly and return ONLY valid JSON: {\"dos\":[],\"donts\":[]}\n\n$text"
          }
        ],
        "temperature": 0.2
      }),
    );

    final decoded = jsonDecode(response.body);
    String content =
    decoded["choices"][0]["message"]["content"];

    content =
        content.replaceAll("```json", "").replaceAll("```", "").trim();

    return jsonDecode(content);
  }

  // ===============================
  // PREMIUM POPUP
  // ===============================
  void showPremiumPopup(List dos, List donts) {
    showDialog(
      context: context,
      builder: (_) => DefaultTabController(
        length: 2,
        child: Dialog(
          shape:
          RoundedRectangleBorder(borderRadius: BorderRadius.circular(20)),
          child: Container(
            padding: const EdgeInsets.all(20),
            height: 450,
            child: Column(
              children: [
                const Text(
                  "AI Generated Directives",
                  style: TextStyle(
                      fontSize: 20,
                      fontWeight: FontWeight.bold),
                ),
                const SizedBox(height: 10),
                const TabBar(
                  labelColor: Colors.black,
                  indicatorColor: Colors.deepPurple,
                  tabs: [
                    Tab(text: "Do's"),
                    Tab(text: "Don'ts"),
                  ],
                ),
                const SizedBox(height: 10),
                Expanded(
                  child: TabBarView(
                    children: [
                      buildList(dos, Colors.green.shade50),
                      buildList(donts, Colors.red.shade50),
                    ],
                  ),
                ),
                const Divider(),
                const Text(
                  "Generated by AI",
                  style: TextStyle(
                      fontSize: 12,
                      fontStyle: FontStyle.italic,
                      color: Colors.grey),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }

  Widget buildList(List items, Color color) {
    return ListView.builder(
      itemCount: items.length,
      itemBuilder: (context, index) {
        return Card(
          color: color,
          shape:
          RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
          child: Padding(
            padding: const EdgeInsets.all(12),
            child: Text(items[index]),
          ),
        );
      },
    );
  }

  // ===============================
  // PREMIUM SCREEN UI
  // ===============================
  @override
  Widget build(BuildContext context) {
    return Container(
      decoration: const BoxDecoration(
        gradient: LinearGradient(
          colors: [Color(0xFF1E1E2C), Color(0xFF2E2E48)],
          begin: Alignment.topCenter,
          end: Alignment.bottomCenter,
        ),
      ),
      child: Center(
        child: isLoading
            ? const CircularProgressIndicator(color: Colors.white)
            : Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            const Icon(Icons.auto_awesome,
                color: Colors.deepPurpleAccent, size: 50),
            const SizedBox(height: 20),
            const Text(
              "AI Based Public Directives",
              style: TextStyle(
                fontSize: 26,
                fontWeight: FontWeight.bold,
                color: Colors.white,
                letterSpacing: 1.2,
              ),
              textAlign: TextAlign.center,
            ),
            const SizedBox(height: 10),
            const Text(
              "Upload a document and let AI extract structured Do's & Don'ts",
              style: TextStyle(
                  color: Colors.white70,
                  fontSize: 14),
              textAlign: TextAlign.center,
            ),
            const SizedBox(height: 40),
            ElevatedButton(
              style: ElevatedButton.styleFrom(
                padding: const EdgeInsets.symmetric(
                    horizontal: 30, vertical: 15),
                backgroundColor: Colors.deepPurple,
                shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(30),
                ),
                elevation: 8,
              ),
              onPressed: pickAndProcessFile,
              child: const Text(
                "Upload PDF & Generate",
                style: TextStyle(
                  fontSize: 16,
                  color: Colors.white, // 👈 makes text white
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}
