// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfsymtN_4mTmRPgvemkfTDOn44MGPaupA',
    appId: '1:1078911825322:web:4d817e59581993db3427d3',
    messagingSenderId: '1078911825322',
    projectId: 'ieee-com-hack',
    authDomain: 'ieee-com-hack.firebaseapp.com',
    storageBucket: 'ieee-com-hack.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARNixjOcq0qQXCoG0DX1pEIuq_hmttZZ0',
    appId: '1:1078911825322:android:1b3a8b7e0be018ad3427d3',
    messagingSenderId: '1078911825322',
    projectId: 'ieee-com-hack',
    storageBucket: 'ieee-com-hack.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB06fju0ODCkXhxrElYuPEA0Ybm4Bewgok',
    appId: '1:1078911825322:ios:93e620e911a955ef3427d3',
    messagingSenderId: '1078911825322',
    projectId: 'ieee-com-hack',
    storageBucket: 'ieee-com-hack.firebasestorage.app',
    iosBundleId: 'com.eternals.ieeeComHack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB06fju0ODCkXhxrElYuPEA0Ybm4Bewgok',
    appId: '1:1078911825322:ios:93e620e911a955ef3427d3',
    messagingSenderId: '1078911825322',
    projectId: 'ieee-com-hack',
    storageBucket: 'ieee-com-hack.firebasestorage.app',
    iosBundleId: 'com.eternals.ieeeComHack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfsymtN_4mTmRPgvemkfTDOn44MGPaupA',
    appId: '1:1078911825322:web:366c28d9d0c9025a3427d3',
    messagingSenderId: '1078911825322',
    projectId: 'ieee-com-hack',
    authDomain: 'ieee-com-hack.firebaseapp.com',
    storageBucket: 'ieee-com-hack.firebasestorage.app',
  );
}
